name: aniverse_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  video_player: ^2.8.1
  chewie: ^1.7.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
