name: aniverse_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.4.1+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  video_player: ^2.8.1
  chewie: ^1.7.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/aniverse_icon.png"
  adaptive_icon_background: "#0E0E0E"
  adaptive_icon_foreground: "assets/icon/aniverse_icon_fg.png"
